name: Build
on:
  pull_request:
  push:
    branches:
      - "**"
  workflow_call:
    inputs:
      ref:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        if: ${{ inputs.ref == '' }}
        uses: actions/checkout@v3.2.0
      - name: Checkout requested ref
        if: ${{ inputs.ref != '' }}
        uses: actions/checkout@v3.2.0
        with:
          ref: ${{ inputs.ref }}
      - uses: gradle/wrapper-validation-action@v1.0.6
      - name: Setup JDK 17
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 17
          distribution: temurin
      - name: Mark gradlew as an executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Artifacts
          path: build/libs