name: Build
on:
  pull_request:
  push:
    branches:
      - "**"
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: gradle/wrapper-validation-action@v1.0.5
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.10.0
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Mark gradlew as an executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Upload artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Artifacts
          path: build/libs