name: Publish
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-[A-Z]+

jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish_mc:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3.0.1
        with:
          name: Artifacts
          path: build/libs
      - name: Generate changelog
        id: changelog_generator
        uses: Helmisek/conventional-changelog-generator@v1.0.6-release
        with:
          token: ${{ github.token }}
          commit-types: "BREAKING CHANGE:Breaking Changes,feat:Features,fix:Bug Fixes"
          current-tag: ${{ github.ref_name }
      - name: Determine channel
        id: channel
        run: |
          if [[ ${{ github.ref_name }} == v0.* ]]; then
            echo "CHANNEL=alpha" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref_name }} == *-SNAPSHOT ]]; then
            echo "CHANNEL=beta" >> $GITHUB_OUTPUT
          else
            echo "CHANNEL=release" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - uses: Kir-Antipov/mc-publish@v3.2
        name: Publish
        with:
          changelog: ${{ steps.changelog_generator.changelog }}
          name: "More Apoli ${{ github.ref_name }}"
          version: ${{ github.ref_name }}
          version-type: ${{ steps.channel.CHANNEL }}
          loaders: [ fabric ]
          game-versions: [ 1.19.2 ]
          modrinth-id: bEEBabZs
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-tag: ${{ github.ref_name }}
          github-prerelease: ${{ steps.channel.CHANNEL != 'release' }}
          github-token: ${{ github.token }}